export const config = {
  FIREBASE_API_KEY: process.env.FIREBASE_API_KEY,
  FIREBASE_AUTHDOMAIN: process.env.FIREBASE_AUTHDOMAIN,
  FIREBASE_DATABASEURL: process.env.FIREBASE_DATABASEURL,
  FIREBASE_PROJECTID: process.env.FIREBASE_PROJECTID,
  FIREBASE_STORAGEBUCKET: process.env.FIREBASE_STORAGEBUCKET,
  FIREBASE_MESSAGINGSENDERID: process.env.FIREBASE_MESSAGINGSENDERID,
  FIREBASE_APPID: process.env.FIREBASE_APPID,
};
